### ISSUE TITLE
possibly wrong copy-paste in article

### ISSUE THREAD

**Issue by niya3** [pagnihotry/golang_samples#1]
I've found that article http://p.agnihotry.com/post/understanding_the_context_package_in_golang/ contains the same line `ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(2 * time.Second))` three times while it illustrating three different calls:

- context.WithCancel
- context.WithTimeout
- context.WithDeadline

It seems to me that smth gone wrong :) and possibly there must be three different example lines instead of the same one.

**Comment by pagnihotry** [comment]
Thanks @niya3 for pointing this out. I have updated the post.
